name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 9.0.x

      - name: Install required workloads
        run: |
          dotnet workload install aspire

      - name: Install reportgenerator
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Start dependencies (docker-compose)
        run: |
          docker compose -f ./docker-compose.yml up -d
        working-directory: ${{env.working-directory}}

      - name: Wait for SQL Server container
        run: sleep 30s
        shell: bash
        
      - name: Restore
        run: |
          find src -name '*.csproj' ! -path '*/libs/*' -exec dotnet restore {} -p:UseProjectReferences=false \;
        working-directory: ${{env.working-directory}}
      
      - name: Build
        run: |
          find src -name '*.csproj' ! -path '*/libs/*' -exec dotnet build {} --no-restore -c Release -p:UseProjectReferences=false \;
        working-directory: ${{env.working-directory}}

      - name: Test with Coverage
        run: |
          find tests -name '*.csproj' -exec dotnet test {} --no-build --verbosity normal -p:UseProjectReferences=false \;
        working-directory: ${{env.working-directory}}

